### ISSUE TITLE
"play current scene" option no longer works while multiple tabs open after v2.3.8

### ISSUE THREAD

**Issue by EoinBurke93** [philpw99/Stash_Helper#10]
In v2.3.8 and below, you were able to Alt P in the browser and it would play the scene from the first tab. You could reorder you tabs and just Alt P the newly dragged first tab.
Now it either just plays the original first tab even if it was moved, or if that tab was closed. It would crash Stash Helper (not SashApp though)
To me that's a feature that you should have even in your Read Me docs, almost as good as being able to Alt P whatever tab your on, but obviously adding that feature would be a lot harder than reimplementing what you had V2.3.8 and older.

Hopefully you'll find out what broke it, and I appreciate your work.

Tested with Firefox & Chrome

**Comment by philpw99** [comment]
The multi-tab enumeration is tricky, and I thought I fixed it but obviously it's not. Yeah, I will check it out.

**Comment by philpw99** [comment]
The new v.2.3.11 might finally fix the multi-tab problem. Please try it out, thank you !
