### ISSUE TITLE
[FEATURE REQUEST] Add "remember my answer to this question" to "Scraper Manager" dialogues

### ISSUE THREAD

**Issue by furopi** [philpw99/Stash_Helper#12]
Sorry, I accidentely hit the enter button while writing the title. I really appreciate the work you've to create a imho very usefull app!

I'could explain this request more detailed, but I guess the title should say evrything needed. Without further blabla, thank you even for reading that far.

Kind regards,
Florian

**Comment by philpw99** [comment]
Cool. Thank you for suggesting it ! This should be no problem.

**Comment by philpw99** [comment]
A quick fix is here. maybe more dialogs need the "Always Yes" and "Always No" option too ?
https://github.com/philpw99/Stash_Helper/releases/tag/v2.3.12

**Comment by furopi** [comment]
Awesome reaction time!! One more suggestion would be add this option to the dialogue shown below (also in the scrapers manager)?
<img width="312" alt="2022-11-17 19_14_41-Error getting scraper file" src="https://user-images.githubusercontent.com/36579099/202525387-d5f9c9b6-bc73-42f1-a1b2-3c5f5f940d73.png">
