### ISSUE TITLE
"Error In Browser" with first startup

### ISSUE THREAD

**Issue by IIEleven11** [philpw99/Stash_Helper#15]
Windows 10
Stash Version - 02c2ad3f
Browser - OperaGX

After successful installation. Upon clicking the program in the start menu I receive this error - "Now we are trying to force update of webdriver....." followed by "Something is wrong with the browsers driver. Cannot continue. WinHTTP status code:0 Script line:-1". 

Steps taken to solve- I tried updating the OperaGX browser, It was out of date but no change with stash helper.
I tried using the latest firefox also getting the same errors.

**Comment by IIEleven11** [comment]
I had to do a OS reinstall and it cleared it, was probably on my end. Everything works just fine now

**Comment by philpw99** [comment]
Cool ! Good to know it works !
