### ISSUE TITLE
how do i send selected files to potplayer?

### ISSUE THREAD

**Issue by githubxnoob** [philpw99/Stash_Helper#17]
i search scenes and select videos i like using that checkmark button. now i want to send these to potplayer  but the keyboard shortcut sends the whole results to player i dont want that.

i only want selected videos? is that possible?

**Comment by philpw99** [comment]
Use the "Play List" feature please.
Ctrl-Alt-A to add scene/movie to the list, then Ctrl-Alt-P to play the videos in your playlist.
I don't recommend sending pictures to the play list though, even you can actually do that.

**Comment by philpw99** [comment]
Sorry that I didn't realize my code was broken. Stash Helper was designed to let you filter your scenes and send them all to the media player, or add them to the built-in playlist.
A single misjudgement in a "if" statement made SH send all files to the player. Now it's fixed and it should work as intended.
Also now you can use middle mouse button to play the scene/movie, or Ctrl-MidMouseButton to send it to the playlist.
https://github.com/philpw99/Stash_Helper/releases/tag/v2.4.6
