### ISSUE TITLE
[feature request] better potplayer integration.

### ISSUE THREAD

**Issue by githubxnoob** [philpw99/Stash_Helper#18]
compared to the stash webplayer potplayer is 100 times better. it has custom keyboard shortcuts, better playback controls.

alt+p shortcut is great. but can we have some kind of feature that automatically takes over the video stream and pass it to potplayer?
when stashapp starts playing video i want the stashapp helper to pause that video automatically and quickly pass it to potplayer.

it would be even better if it somehow detects the videos in queue and also pass it to pot player

**Comment by philpw99** [comment]
In the Settings->Interface-Scene Player, you can disable the auto-start function.
The Stash queue feature has been changing and it's not opened to query, so I use my own play list for this purpose.
