### ISSUE TITLE
default chrome profile get web driver error, stash version 18.0

### ISSUE THREAD

**Issue by saccohuo** [philpw99/Stash_Helper#19]
![image](https://user-images.githubusercontent.com/13887263/206900374-260b14e1-5e2c-4f10-af4e-49e8bf65868a.png)
```
---------------------------
Error in Browser
---------------------------
Now we are trying a force update of webdriver.

Hopefully it will fix the problem. If not, please create an issue in repo, thank you!
---------------------------
确定   
---------------------------
```

click ok and get

![image](https://user-images.githubusercontent.com/13887263/206900391-e202693a-fc2e-4845-b75c-870200eafd4d.png)

```
---------------------------
Oops !
---------------------------
Something wrong with the browser's driver. Cannot continue.

WinHTTP status code:500

Script Line:-1
---------------------------
确定   
---------------------------
```

**Comment by saccohuo** [comment]
> I just tested it with both v17 an v18 with Chrome. They work fine in my machine. Please take a look at the files in `%appdata% \Webdriver\` folder. You should see the "chromedriver.exe" there. Please open the "chrome.log" and check what's wrong with it. If possible, please upload the file here? Or you can just delete those two files and try again.

Can you provide your email, I can send it with email.

**Comment by philpw99** [comment]
Sure, you can send the log to philpw99@gmail.com

**Comment by philpw99** [comment]
Thank you for your email !
Just have time to check your log file in the mail. It's unexpectedly long.
Basically at the end of the log, it tries to open:
`C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`
but it was obviously wrong location. That file is actually in:
`C:\Program Files\Google\Chrome\Application\chrome.exe`
So basically the Webdriver get the 32bit/64bit information wrong. Maybe you have installed 32bit Chrome then uninstalled it, then you use 64bit of Chrome?
I will look into this matter more to see what exactly happened.

**Comment by saccohuo** [comment]
It is 64bit version Chrome, I checked it.
![image](https://user-images.githubusercontent.com/13887263/208029065-314af713-98c1-4694-b69b-ced4696463a8.png)

**Comment by philpw99** [comment]
You can actually specify the location of chrome.exe by clicking on "Browser EXE location" like below:
<img src="https://user-images.githubusercontent.com/22040708/208204183-c74f707f-e8a9-4344-90d9-e8b196d9c872.png" width=500>
and browse to the location of your chrome.exe
This way Stash Helper will always launch the browser in that specified location.

**Comment by saccohuo** [comment]
I cannot specify it now, it will exit automatically with the following two images.


> ![image](https://user-images.githubusercontent.com/13887263/206900374-260b14e1-5e2c-4f10-af4e-49e8bf65868a.png)

> ![image](https://user-images.githubusercontent.com/13887263/206900391-e202693a-fc2e-4845-b75c-870200eafd4d.png)

**Comment by philpw99** [comment]
OK, I see the problem now.
First you need to use Regedit to change the registry settings in:
Computer\HKEY_CURRENT_USER\Software\Stash_Helper
Change the "BrowserLocation" data to empty, then try to run Stash_Helper again.
If it is not working, change the "Browser" from "Chrome" to "Edge" or "FireFox".
After that you should be able to run.

**Comment by saccohuo** [comment]
I find the reg key here, but the `BrowserLocation` is already empty, I change the `Profile` from `Default` to `Private`. It works. 
But I change the settings to `Default` or `Firefox`, it breaks again. Error msgs are same as above.

**Comment by philpw99** [comment]
Thank you ! What you tell me here will improve the program soon. 
But I am a little confused now. The setting of "Default" and "Private" is not that much different.
Maybe your user profile is not in C:\User\xxx ?
Anyway, my program do assume the user profile location is in C: drive. It's quite a bug. I will fix it.

**Comment by philpw99** [comment]
Maybe you can give the new v2.4.3 a try? Thank you !
https://github.com/philpw99/Stash_Helper/releases/tag/v2.4.3

**Comment by saccohuo** [comment]
> Thank you ! What you tell me here will improve the program soon. But I am a little confused now. The setting of "Default" and "Private" is not that much different. Maybe your user profile is not in C:\User\xxx ? Anyway, my program do assume the user profile location is in C: drive. It's quite a bug. I will fix it.

My chrome profile is in C Drive, new v2.4.3 throw the same error msg too.

**Comment by philpw99** [comment]
In the previous post, I thought you were having a problem because Stash Helper was trying to run chrome.exe at the 32bit location:
`C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`
That's what it showed in the log you sent me.
Now since the "Private" profile works and `BrowserLocation` is empty, this becomes strange. It means the Stash Helper runs the chrome.exe correctly, but still there is a problem running chrome browser.
So I suggest that you might need to take a look at your various browser plug-ins. One of your plug-ins might cause the problem.
Or your browser profile is not in :
`"C:\Users\YourUserName\AppData\Local\Google\Chrome\User Data\"`

**Comment by philpw99** [comment]
After some code inspection, I found that the code indeed handles unicodes in Json string in an incomplete or wrong way.
This problem exists in other functions that involves unicode too.
So now the new release will make the profile path more utf8 friendly. Hopefully it will fix the problem.
https://github.com/philpw99/Stash_Helper/releases/tag/v2.4.4

**Comment by saccohuo** [comment]
Tried v2.4.4, the same error. 
The profile path is not unicode, and I checked my profile is in C:\Users\YourUserName\AppData\Local\Google\Chrome\User Data\

**Comment by philpw99** [comment]
So now it seems to boil down to plugins.
I went back to the log you sent me. In the last few lines, you can see:
`Launching chrome: "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" ... RESPONSE InitSession ERROR unknown error: Chrome failed to start: exited normally.`
The 64bit chrome.exe is not there. It should be in `C:\Program Files\Google\Chrome\Application\chrome.exe`
Therefore you probably need to manually set the exe location by using the "Browse EXE Location" button as the previously post.

**Comment by saccohuo** [comment]
> So now it seems to boil down to plugins. I went back to the log you sent me. In the last few lines, you can see: `Launching chrome: "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" ... RESPONSE InitSession ERROR unknown error: Chrome failed to start: exited normally.` The 64bit chrome.exe is not there. It should be in `C:\Program Files\Google\Chrome\Application\chrome.exe` Therefore you probably need to manually set the exe location by using the "Browse EXE Location" button as the previously post.

However my chrome maybe installed in the 32bit location ever, maybe it is a not very common situation.

**Comment by Viskym** [comment]
experienced identical issue in Edge. All issues same with [saccohuo](https://github.com/saccohuo). Thank you for debugging in advance!

**Comment by philpw99** [comment]
Thank you Viskym! Now I see this is a problem that's common. Something in Webdriver changed, the things that worked before no longer works. I will dig into it and see what is going on.

**Comment by philpw99** [comment]
@saccohuo  It seems you are right all along. It is not the failure of finding the right exe, but the changes with the specification of "Browser Capability" in the new chrome, though I still don't understand why my own chrome, which is the same version like yours, works perfectly.

**Comment by philpw99** [comment]
@saccohuo  Finally I was able to figure it out:
When Chrome crashed or having problems, it might still remain in the memory. Then every time you launch Stash Helper, it will give you the same error, no matter how you change the program.
To fix it, just need to use Task Manager to close all running Chrome in the memory.
@Viskym  Microsoft switched their browser to chrome-based, so the settings were changed and more similar to Chrome. I made the change and it seems work fine. Also you need to make sure all Microsoft Edge instances are closed before you run Stash Helper.
Anyway, now here is the new and improved v.2.4.5
https://github.com/philpw99/Stash_Helper/releases/tag/v2.4.5

**Comment by saccohuo** [comment]
> @saccohuo Finally I was able to figure it out: When Chrome crashed or having problems, it might still remain in the memory. Then every time you launch Stash Helper, it will give you the same error, no matter how you change the program. To fix it, just need to use Task Manager to close all running Chrome in the memory. @Viskym Microsoft switched their browser to chrome-based, so the settings were changed and more similar to Chrome. I made the change and it seems work fine. Also you need to make sure all Microsoft Edge instances are closed before you run Stash Helper. Anyway, now here is the new and improved v.2.4.5 https://github.com/philpw99/Stash_Helper/releases/tag/v2.4.5

After close all `chrome.exe` process and `chromedriver.exe` process, install the recent `v2.4.5`, it works well.
Thanks for that!!!
