### ISSUE TITLE
Shortcut keys

### ISSUE THREAD

**Issue by jjkim87** [philpw99/Stash_Helper#2]
Hello, 

I am very satisfied with Stash's powerful cleaning function, but whenever I play a video, my old CPU on my PC is overworked, so I was looking for a way to play it on a local player such as Potplayer. Thank you for developing a good program.

​If there is one suggestion, it would be nice if you could put a shortcut key in Play Current Scene/Movie/Gallery/Images or set it up

​Thank you again.^^

**Comment by philpw99** [comment]
OK, thanks for the kind words and suggestion. I will implement this shortcut very soon.
