### ISSUE TITLE
Feature request: use Pake to export stash as an app, like PWA

### ISSUE THREAD

**Issue by saccohuo** [philpw99/Stash_Helper#20]
Feature request: use Pake to export stash as an app, like PWA

https://github.com/tw93/Pake

**Comment by philpw99** [comment]
Sorry, if I do that, the guys in Stash might be angry at me.
Stash is their own baby. They spent a lot of time and effort to make it work nicely in all platforms. They should be the one who do the packaging, not me. I am the one who help Stash's translation of Simplified Chinese, which I hope it will be easy enough for us Chinese.
My program is merely a helper to add some features to their excellent program. I need to be in good terms with them.
