### ISSUE TITLE
better send to playlist support.

### ISSUE THREAD

**Issue by githubxnoob** [philpw99/Stash_Helper#21]
when i go to tags and use the shortcut to send to player it says  "sorry but this kind of collections are not supported yet"

please let us send all videos in tags / performers/ studio to playlist.

new videos get added or deleted very frequently its a chore to maintain them in two different places.

**Comment by philpw99** [comment]
OK, will look into it. 
The original function to turn a URL into a Graphql request is getting too long and complicated. That's why the query failed before.
So I guess I will use different functions for tags, performers and studios.

**Comment by githubxnoob** [comment]
> OK, will look into it. The original function to turn a URL into a Graphql request is getting too long and complicated. That's why the query failed before. So I guess I will use different functions for tags, performers and studios. Right now I am busy with the new Custom Javascript. Very exciting possibilities.

by custom javascript do you mean letting users run their own javascript?

**Comment by philpw99** [comment]
There is a lot of work just to make the scene/movie/picture/gallery works. 
Tags/performers and studio will require a lot more coding.
Right now I am not interested in making this program any more. So sorry that it will not happen.
I will just do maintenance for Stash Helper.
