### ISSUE TITLE
A couple of questions about playlists.

### ISSUE THREAD

**Issue by MorningLiteMountain** [philpw99/Stash_Helper#22]
Just making sure I'm not missing anything but is there a way of sending multiple items/scenes to the playlist? Right now I have to go to the each individual scene's page before I can add it. Is there no way to select multiple scenes and add them to the playlist?

Second, after I send the list to an external player (PotPlayer in my case) the file names are blank, only each scene's playtime shows up. That means I have to remember what order I added however many scenes or play through each one until I find the one I want. I'm wondering if this is true with all the supported media players or just a quirk of PotPlayer in particular.

Thanks

**Comment by philpw99** [comment]
Sorry, I was very late to this.
I will check the play list again and see.

**Comment by philpw99** [comment]
The playlist had the scene title like "scene: xxxxx.mp4" before. The new Stash had some change and now the "title" property is empty for most scenes. I will make the change that if title is empty, it will use basename instead.

Currently the pop-up menu will only allow you to add one scene at a time. I will see if I can add "all the current scenes" to the list.
Actually, if you use "Ctrl-Alt-A", you can add all the scenes currently filtered.
