### ISSUE TITLE
Add option to open mini-menu with a key modifier plus middle click. Or even better, right click (bottom left of cursor)

### ISSUE THREAD

**Issue by EoinBurke93** [philpw99/Stash_Helper#24]
It would be great to be able to set a modifier with the middle button click to open the mini-menu.
I personally use middle click almost as much as a use left click while browsing. Opening links in new tab and closing tabs etc. 
So having a the menu pop up so often made me map my middle button in firefox, while stash is running to ctrl+click for now.

I think it really should be the right click menu. If it's put bottom left of mouse cursor it would not be in the way of the context menu and then to stop it staying on the screen, have the script wait for any second right click to close it again rather than clicking cancel (or do a check to see if user left clicked outside the menu and then close it).

**Comment by philpw99** [comment]
OK, I will change it to right click + Control. Seems it does make more sense.
