### ISSUE TITLE
Cannot fetch webdriver

### ISSUE THREAD

**Issue by EldrinSMP** [philpw99/Stash_Helper#25]
## Issue
When I installed Stash_Helper v.2.4.8  I chose Chrome as my browser. Now, every time I try to run the program, I get the following error:
<img width="296" alt="AutoIt3_x64_DgP6yYoqeO" src="https://github.com/philpw99/Stash_Helper/assets/134807078/81baacec-992e-4579-a724-a8a8347379e0">

Program then closes. 

## Replication
This happens every time I try to open the Stash_Helper or Stash_Helper (x64) link. I have also tried to open it from file explorer using the AutoIt3.exe program referencing the Stash_Helper A3x file and it happens there as well.

## Attempts to fix issue
>Uninstalled via the included  uninstaller, the windows uninstaller, iOBit uninstaller, Glary Unitalities Uninstaller, and run Glary Utilities System cleaner as well as IOBit Advanced System cleaner (All on different installs), reboot, and reinstall Stash Helper. 
>Edit: It appears I missed some of the registry entries and my uninstaller programs nor registry cleaners are not as thorough as I thought. Registry keys were being left behind, explaining why the problem persists beyond reinstalls. A workaround has been found, changing the registry key to a different browser will allow me to use the program, but the problem persists if I use Chrome as the browser of choice. 

>Added exceptions to all Firewalls.

>_**DISABLED**_ all firewalls. Restarted.

>_**DISABLED**_ all VPNS. Restarted. 

>Changed Chrome to default browser. 

## Operating Syastem
Windows 11 Pro Version	10.0.22621 Build 22621

## Coments
I recently updated to Windows 11 Pro from Windows 11 Home via a clean format and reinstall. Stash Halper was working on the previous incarnation of my system.

## Feature Request
Add Vivaldi as a supported browser.

**Comment by Reimsee** [comment]
Same Problem here. I also don't find a workarround. Uninstall and reinstall doesn't reset the settings.

**Comment by EldrinSMP** [comment]
@Reimsee I did some digging, and actually found a workaround in the Wiki. It will at least let you re-run the onbarding / First Run screen, or change the browser directly to another browser, like Firefox. 

Open regedit and search for the "HKEY_CURRENT_USER\Software\Stash_Helper". Then find the "Browser" entry and delete the data in it. The restart your computer. This should cause the First Run sequence to run again, and you can change your browser. I am not sure if Chrome is still broken or not, I've been using Firefox.  Alternatively, if you have Firefox or Opera installed, you can change the data value direcly to either "Firefox" or "Opera" and it will run Stash in either of these.  I hope this helps, since it seems the developer or anyone else is monitoring this.

**Comment by philpw99** [comment]
Agree. Right now I am not actively updating this app, because the web driver implement is quite buggy, especially for Chrome browser. When a new Chrome browser is released, the driver needs to be updated. Then people who use the old ones will have issues like this. Firefox and Edge have less problems.

I will keep this thread opened, so maybe others will see it as well.
