### ISSUE TITLE
Query: Does SH need to open browser? (SH unable to load in edge)

### ISSUE THREAD

**Issue by Dark-Obsidian** [philpw99/Stash_Helper#26]
### Summary
- Does SH need to open the browser windows itself in order to work? (i.e. if I just open stash from a regular shortcut, or by running `stash-win.exe` will SH integrations work?)
- SH sounds great and I was looking forward to using several of the features, however SH was unable to load Edge 'normally' and so would auto-close after a few seconds and so I couldn't use it at all

### Further Info
- I had stash already open in Edge, in my main window that had other tabs open also
- I configured SH to use Edge in the initial setup wizard
- When SH ran, it didn't open a new tab in my existing windows as I thought it would (e.g. this is how `stash-win.exe` works) and instead opened stash in a new private window (while I appreciate the privacy consideration, I would've preferred to just have it run in my main window/profile)
- I open SH settings and saw there was an option to run SH in the `default profile` so selected this and restarted SH
- SH then opened Edge, but **not the default profile** instead it opened a secondary profile I had setup in Edge
- I then got error messages about webdriver not working and SH auto-closes a few seconds later...
![Screenshot 2023-10-08 124951](https://github.com/philpw99/Stash_Helper/assets/140384474/1b27c001-670d-406d-adfd-bb6eb2de0b9b)
![Screenshot 2023-10-08 125108](https://github.com/philpw99/Stash_Helper/assets/140384474/94dec15e-90e1-4fa3-935c-c550116d8e26)

### Impact
- Whilst running in a private session was not ideal, as I didn't have access to any of my other tabs, bookmarks, extensions, etc, it did at least open stash... however now that SH auto-closes after a few seconds I am not sure how to revert back :-/
- If I could just use the SH features in my regular Edge session (i.e. the one that is already running, where I have various tabs (incl. several stash tabs open) already open that would be great! Is this possible?
- I have stash set to `not open window on launch` as I already stash open and pinned in my browser for easy access, i.e. I just double-click `stash-win.exe` and then alt+tab to my browser and use a tab I already have open, rather than stash opening it for me... Can SH work like this too?

Thanks!

**Comment by philpw99** [comment]
Thank you for the detail info !

SH will try to detect if a Stash is already running or not. If it's not running, it will run the stash-win.exe. Otherwise it will just open a browser instance.

You can close that browser and let SH runs in the background. SH will open a new browser instance when you click on its menu.

The problem of Edge is probably due to the Web driver update again. I haven't updated the code for web driver for a while, so it probably stop working for now.

The program do need some improving. It should try to attach an existing browser first, only when it fails it should create a new instance. I will do some updates and see if this is possible.

**Comment by Dark-Obsidian** [comment]
No problem, I am naturally very detailed (it takes me ages to write anything! 😀)

Thanks for replying straight away and looking into this - hopefully Microsoft don't make this too hard for you to fix or make you spend ages to get this working again! (I agree M/S are annoying but I really like the *vertical tabs* feature, which is only in Edge I think)

### Extra info
After reading your message I did some additional checking (hopefully this helps)...
- I checked that `stash-win.exe` was **NOT** running, opened Edge with stash tabs open, and then ran SH (`AutoIt3_x64.exe`)
- I did this again, but this time made sure `stash-win.exe` **WAS** running before running `AutoIt3_x64.exe`
- Both times SH opened a new Edge window on an unexpected Edge profile, and both times it did not seem to open a page for `http://localhost:9999`
- Interestingly, in the second test (`stash-win.exe` **WAS** running before I started SH), when SH closed/crashed it also caused `stash-win.exe` to stop running too!

### How to reset?
- I am not sure how to reset SH
- I tried running it without the `Stash_Helper.a3x` parameter, but this just asked for a `.a3x` file
- AFAIK the only way to get back to the "welcome wizard" is to now uninstall SH completely and install it again, but if there is an easier way please let me know

![image](https://github.com/philpw99/Stash_Helper/assets/140384474/74a46082-eb26-4e87-bdf1-e04dc7b17502)

**Comment by Dark-Obsidian** [comment]
### Extra: Local Webdriver version info...
- I was copying some files in my `%AppData%` folder and noticed the new `Webdriver` folder (which I guess is the file / folder that SH uses?)
- I was curious if I could fix this myself / force it to upgrade to the latest version, but it seems like maybe SH has a hard-coded value for Webdriver or something?...
- I deleted `msedgedriver.exe` and downloaded the latest one from https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver
- When I ran SH, I still got the error saying SH was forcing an update of Webdriver, but it seemed like SH actually ***downgraded*** webdriver? 😕
![webdriver](https://github.com/philpw99/Stash_Helper/assets/140384474/38f6abe9-7014-4664-9dec-0bae782120db)

**Comment by philpw99** [comment]
The new version 2.4.9 added a new function to let you choose the browser again.
The error dialog will give you "Yes" "No" "Cancel" choice. Use "No", and next time Stash_Helper will let you choose a new browser.
This time use Firefox. I am really fed up with Chrome and Edge.
