### ISSUE TITLE
Middle Button Alternatives

### ISSUE THREAD

**Issue by bogbrush1** [philpw99/Stash_Helper#27]
Hi this is a great Stash addition but I can't get the context menu to work.

A lot of modern laptops don't come with a middle button on the trackpad (why?) and I don't get an option to change gestures to middle click in my trackpad settings. Any prospect in an update of the user being able to choose their button combination to open the context menu eg CTRL + right click?

Thanks for your time

**Comment by philpw99** [comment]
Oh, that's good suggestion. I will add this feature to the next release.

**Comment by bogbrush1** [comment]
Much appreciated for the response and MS link (but the suggetsion doesn't work with every laptop - depends a Synaptics manged trackpad being intsalled etc, which isn't the case for many devices)

**Comment by philpw99** [comment]
OK, the new version 2.4.10 is out. Ctrl + Right mouse button feature added. Change the combo in the settings.

**Comment by bogbrush1** [comment]
Thanks, much appreciated!!!!

**Comment by bogbrush1** [comment]
Awesome, thanks for the update!
