### ISSUE TITLE
Error getting data from the stash server

### ISSUE THREAD

**Issue by stublu** [philpw99/Stash_Helper#28]
When clicking play in external player I get "Error getting data from the stash server. Returned code:422". It happens regardless of which player is selected. Weirdly if I add the scene to a playlist then click send playlist to external player the playlist loads in the player fine. 

Only seems to happen when running from a remote setup, when running local it works fine. 

![image](https://github.com/philpw99/Stash_Helper/assets/53180585/4364f6d9-f8f3-4a54-aacb-4c8d683f335c)

**Comment by philpw99** [comment]
Thank you for creating this issue ! It was a stupid mistake in code, which works before but no more. The new update will surely fix it.
