### ISSUE TITLE
Not working with a reverse proxy

### ISSUE THREAD

**Issue by Johnnybegood90** [philpw99/Stash_Helper#3]
The application immediately crash if you set an URL and not an IP.

**Comment by philpw99** [comment]
Wait, maybe you can set the app to remote mode then set the URL? Did you try that?

**Comment by Johnnybegood90** [comment]
Yes, but still crashing.

**Comment by Johnnybegood90** [comment]
Please take a look: https://github.com/stashapp/stash/wiki/Reverse-proxy

**Comment by philpw99** [comment]
So is there a website like that for me to test? This way we can both save lots of time. 
If you like the idea, send the link to my email philpw99@gmail.com please.

**Comment by Johnnybegood90** [comment]
Mail sent.

**Comment by philpw99** [comment]
OK, new release of v2.3.4 is out. It should work better with remote websites.

**Comment by philpw99** [comment]
So do you get a chance to check the new release out?

**Comment by Johnnybegood90** [comment]
Hello, sorry for the delay, it's good now, thank you ;)
