### ISSUE TITLE
Error getting chrome driver

### ISSUE THREAD

**Issue by sirhand** [philpw99/Stash_Helper#30]
![image](https://github.com/philpw99/Stash_Helper/assets/31371606/6035cf58-4be0-4b9b-9ef4-cdea88091551)
I get this message when I open Stash_Helper_x64

**Comment by SamTheManScripts** [comment]
i get the same error too

**Comment by hhenne1** [comment]
same

**Comment by ala3131** [comment]
![image](https://github.com/philpw99/Stash_Helper/assets/39478842/81eaa70e-0e75-4b45-b24d-176c87791766)
Here's how I found it.
Prepare a fake "chromedriver.exe" file in the "C:\Users\ala31\AppData\Roaming\Webdriver" folder.
After that, run stash_helper and you should get a warning like the one shown in the picture.
If you press (N) and rerun it, the browser will be selectable again and Firefox will run without any problems.

This article was created with automatic translation.

**Comment by philpw99** [comment]
This is due to WebDriver itself needs to be updated, not just the driver.
So now the new release should fix it, until it doesn't I will update it again.

**Comment by sirhand** [comment]
> This is due to WebDriver itself needs to be updated, not just the driver. So now the new release should fix it, until it stops working I will update it again.

Thanks for the update! I'm excited to check this out.
