### ISSUE TITLE
[Feature request] Click to play with external player

### ISSUE THREAD

**Issue by nokatt** [philpw99/Stash_Helper#4]
I find Stash's forced transcoding quite annoying as it often leads to buffering and some videos still aren't able to play. I would really like to be able to just use an external player and not ever use the web player. Would it be possible to call the external video player with a click instead of the shortcut?

**Comment by philpw99** [comment]
Thank you! This is exactly the reason I started this program. The built-in web player cannot handle the 7k VR videos properly so I have to figure a way to do so.
For your one click purpose, I have a special Stash build here, which has the "Launch Me/ Drag Me" button in the front page of the video. You can try it and see if it works for you or not.

https://github.com/philpw99/stash/releases

**Comment by nokatt** [comment]
Thanks that's great! It's not ideal but better than before :) I use it now in combination with the _Open in VLC_ extension. 

I tried to find a way to use a simple left click to open it in VLC but I have not much experience in web development and even less with browser extensions. It seems the extension mainly uses that function `open` in [worker.js](https://github.com/andy-portmen/open-in-vlc/blob/master/v3/worker.js) to send URLs directly to VLC. Do you think it could be possible to implement something similar without an extension and just with a single left click?

**Comment by philpw99** [comment]
You just need to drag the link to VLC, not click on it.

**Comment by philpw99** [comment]
I see... I will try something else with the special build then.
