### ISSUE TITLE
It takes too long to get StashApp ready. Something is wrong. Exiting.

### ISSUE THREAD

**Issue by reetkont** [philpw99/Stash_Helper#5]
Stash Helper terminates during setup, when launching StashApp. Shows this error:

It takes too long to get StashApp ready. Something is wrong. Exiting.

**Comment by Jdog5449** [comment]
Yep! This is happening to me as well. I think it may be because I was adding this Stash Helper after having installed the Stash app and done most of the scan task.

**Comment by philpw99** [comment]
I see. The Stash program had changed and I didn't catch up with it.
OK, I will update it and make sure it will work.

**Comment by philpw99** [comment]
Now it's updated to v2.3.5
https://github.com/philpw99/Stash_Helper/releases/tag/v2.3.5
It should work with the new 14.0 and 15.0
