### ISSUE TITLE
Error in Browser

### ISSUE THREAD

**Issue by fractalmoth** [philpw99/Stash_Helper#8]
Hi there. I installed Stash Helper selected my windows location for Stash and then selected Chrome. I'm using Vivaldi which is a Chrome fork so thought that would be fine. On running the exe I get this error; 
Something wrong with the browser's driver. Cannot continue. 
WinHTTP status code: 0 
Script LIne:-1
My Stash works fine otherwise. I wanted to try and select another browser for Stash Helper to use instead of Chrome like Edge, but it no longer gives me the option to select which browser I want to use. Does it create files outside of the stash helper directory?

**Comment by philpw99** [comment]
The settings of Stash Helper is in registry settings:
Computer\HKEY_CURRENT_USER\Software\Stash_Helper
There you can change the "Browser" setting to "Edge" or "FireFox". It should fix the problem.

**Comment by fractalmoth** [comment]
Thanks, that fixed the issue. Works fine on Edge.

**Comment by Syunica** [comment]
Same problem for me now..
![image](https://user-images.githubusercontent.com/20818376/228245966-b24395f1-706a-4059-b020-0589a6894cef.png)
im getting this error on every browser
