### ISSUE TITLE
Add option to set path for preferred browser options. Or Change the  'preferred browser' options to include Vivaldi or Chromioum instead of just chrome option.

### ISSUE THREAD

**Issue by EoinBurke93** [philpw99/Stash_Helper#9]
When choosing from the 3 browser options, is there any setting I can change to choose a chrome derivitive, when clicking on the 'Chrome'  option in settings. 
Maybe by allowing custom install path or even better, find the deritives in app. Rather than having to install pure chrome on top of your chrome deritive of choice.
I assume all of the specific chrome settings will apply to chrome derivitives, so is there a way to chose the chrome path, so I can point to chromium instead?

or is there a few lines in the source that I can change to achieve the same thing?

**Comment by philpw99** [comment]
Yes, this is quite doable. All I need to do is just setting a variable for specific path to the binary.

**Comment by philpw99** [comment]
OK, now I had made the changes. Check it out and see if it works:
https://github.com/philpw99/Stash_Helper/releases/tag/v2.3.10

**Comment by EoinBurke93** [comment]
Thank you, Stash Helper opens and closes on the correct category when selected from the dropdown as expected and on it's own profile of Vivaldi.
But does not open scenes/movies etc. selected from the dropdown in stash helper unless I open a new tab for it or go to a second already open tab. It's just an odd bug but it really doesn't matter. Thank you. Now I don't need 2 browsers installed at once. And Vivaldi remembers where I left off where firefox (default profile) didn't.
